print("bye world")
print("bye world")
print("bye world")
print("bye world")
print("bye world")
print("bye world")
print("bye world")
print("bye world")
print("bye world")
print("bye world")
print("hi")
print("text")